# ==============================
# APPLICATION CONFIG
# ==============================
spring.application.name=ecommerce-cart-service

# ==============================
# DATABASE CONFIGURATION
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/cartService
spring.datasource.username=cartServiceUser
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / HIBERNATION CONFIG
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==============================
# ACTUATOR / MONITORING
# ==============================
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# ==============================
# FEIGN CLIENT CONFIGURATION
# ==============================
spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000

# ==============================
# SECURITY CONFIGURATION
# ==============================
jwt.secret=e+4GyEUY2A7k4r1TtEXBFCTg/u0SRs/e9WIdpee2FAE=

# ==============================
# MICROSERVICES BASE URLs
# ==============================
product.service.url=http://localhost:8080
inventory.service.url=http://localhost:8070
order.service.url=http://localhost:8090

# ==============================
# RESILIENCE4J - CIRCUIT BREAKER
# ==============================
resilience4j.circuitbreaker.instances.productService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.productService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.productService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.productService.waitDurationInOpenState=10s

# ==============================
# RESILIENCE4J - RETRY CONFIG
# ==============================
resilience4j.retry.instances.productService.maxAttempts=3
resilience4j.retry.instances.productService.waitDuration=500ms

# ==============================
# SERVER CONFIGURATION
# ==============================
server.port=8060